apiVersion: v1
kind: Pod
metadata:
  name: pollen-train-species
  namespace: stenc-ns
spec:
  securityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  restartPolicy: Never
  containers:
        - name: train-worker
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          image: IMAGE_PLACEHOLDER
          imagePullPolicy: Always
          command:
            - sh
            - -c
            - |
              echo "Preparing container paths..."
              mkdir -p /app/Species_model_Training_data /app/cls_dataset /app/models/species_classifier
              
              echo "Downloading Species Dataset tiles via s5cmd..."
              s5cmd --endpoint-url "$S3_ENDPOINT" --no-verify-ssl sync "s3://$S3_BUCKET/Ostatni/Pollen_latitude/Species_model/Trainig_data/*" /app/Species_model_Training_data/
              
              echo "Extracting image crops to YOLOv8 Classification Dataset..."
              python3 /scripts/extract_crops.py --src /app/Species_model_Training_data/ --out /app/cls_dataset --pad 0.20 --split 0.8
              
              echo "Starting YOLOv8 Species Classification training..."
              export MODEL_DIR=/app/models/species_classifier/
              python3 /scripts/train_species.py --dataset /app/cls_dataset
              
              echo "Uploading best weights to S3..."
              s5cmd --endpoint-url "$S3_ENDPOINT" --no-verify-ssl sync "/app/models/species_classifier/*" "s3://$S3_BUCKET/Ostatni/Pollen_latitude/trained_models/species_classifier/"
          resources:
            limits:
              memory: "64Gi"
              cpu: "8"
              nvidia.com/gpu: "1"
            requests:
              memory: "32Gi"
              cpu: "4"
              nvidia.com/gpu: "1"
          env:
            - name: S3_ENDPOINT
              value: "https://s3.cl4.du.cesnet.cz"
            - name: S3_BUCKET
              value: "bucket"
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: s3-credentials
                  key: access-key
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: s3-credentials
                  key: secret-key
            - name: GMAIL_APP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: email-credentials
                  key: GMAIL_APP_PASSWORD
          volumeMounts:
            - mountPath: /dev/shm
              name: dshm
  volumes:
    - name: dshm
      emptyDir:
        medium: Memory
        sizeLimit: "24Gi"
